apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: revenexx-php
  title: Revenexx PHP
  description: "Revenexx PHP SDK for server-side applications."
  annotations:
    github.com/project-slug: revenexx-sdks/php
    backstage.io/techdocs-ref: url:https://github.com/revenexx-sdks/php/tree/main/
  links:
    - url: https://github.com/revenexx-sdks/php
      title: GitHub Repository
      icon: github
spec:
  type: library
  lifecycle: production
  owner: group:default/developer-experience
  system: revenue-cloud
